### ISSUE TITLE
Create a Github workflow for agc-parser.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [THEGOLDENPRO/anime-girls-and-computers#11]
I think the [agc-parser](https://github.com/THEGOLDENPRO/anime-girls-and-computers/tree/feat/agc-rust-parser/src/agc-parser) is ready to be merged into master branch but before that we need a github workflow that will run it after each pull request and commit just like the ruff workflow we have set up [here](https://github.com/mov-cli/mov-cli/blob/v4/.github/workflows/ruff.yml).

**Comment by ananasmoe** [comment]
https://github.com/THEGOLDENPRO/anime-girls-and-computers/commit/12686d39d0e424f57b3c39a64bf9b21094ba32d7 https://github.com/THEGOLDENPRO/anime-girls-and-computers/commit/c0a196cb35a530149168e4ad38aa2d508542ad0e

<img src="https://github.com/mov-cli/mov-cli/assets/132799819/6f5a5083-bb79-4dc7-bc32-8a0fc8ffad23" width="200">

**Comment by THEGOLDENPRO** [comment]
Thanks 🙏
